ALTER TABLE "RetentionSettings"
  ADD COLUMN IF NOT EXISTS "defaultRebookingIntervalDays" INTEGER NOT NULL DEFAULT 21,
  ADD COLUMN IF NOT EXISTS "dueSoonWindowDays" INTEGER NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS "atRiskAfterDays" INTEGER NOT NULL DEFAULT 30,
  ADD COLUMN IF NOT EXISTS "inactiveAfterDays" INTEGER NOT NULL DEFAULT 90,
  ADD COLUMN IF NOT EXISTS "rebookingAutomationEnabled" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "rebookingCooldownDays" INTEGER NOT NULL DEFAULT 21;

ALTER TABLE "Service"
  ADD COLUMN IF NOT EXISTS "recommendedRebookingIntervalDays" INTEGER;
